### ISSUE TITLE
Missing file:   echo-server-otlp.yaml

### ISSUE THREAD

**Issue by granthbr** [KongHQ-CX/kong-tutorials-observability#1]
I see the   echo-server-otlp.py file for tracing to the endpoint in Jaeger but not the yaml file to apply it to the config. 
Are the expectations to first, run the python file locally, second, convert the echo-server to a dockerfile, push it to docker hub, then, right the manifest file to pull it and apply it to the cluster? Or am I just missing something.... ? thx!

**Comment by tysoekong** [comment]
Hi @granthbr non, you only need to `kubectl apply -f` the file now. I have updated it properly in [#361f32c](https://github.com/KongHQ-CX/kong-tutorials-observability/commit/361f32ce0886a1ff02fa54d93ccc2288f965a3bc)

https://github.com/KongHQ-CX/kong-tutorials-observability/blob/main/01-base-kong/echo-server-otlp.yaml
